import React from 'react'
import {
  SiJavascript,
  SiTypescript,
  SiReact,
  SiNodedotjs,
  SiMongodb,
  SiPostgresql,
  SiTailwindcss,
  SiHtml5,
  SiCss3,
  SiPython,
  SiFlutter,
  SiDocker,
  SiGithub,
  SiAmazonwebservices,
  SiFigma,
  SiOpenai,
  SiCpanel,
} from 'react-icons/si'
import { FaJava } from 'react-icons/fa'

export const TechLogos = {
  JavaScript: (props) => <SiJavascript color="#F7DF1E" {...props} />,
  TypeScript: (props) => <SiTypescript color="#3178C6" {...props} />,
  React: (props) => <SiReact color="#61DAFB" {...props} />,
  NodeJS: (props) => <SiNodedotjs color="#5FA04E" {...props} />,
  MongoDB: (props) => <SiMongodb color="#47A248" {...props} />,
  PostgreSQL: (props) => <SiPostgresql color="#4169E1" {...props} />,
  Tailwind: (props) => <SiTailwindcss color="#06B6D4" {...props} />,
  HTML5: (props) => <SiHtml5 color="#E34F26" {...props} />,
  CSS3: (props) => <SiCss3 color="#1572B6" {...props} />,
  Python: (props) => <SiPython color="#3776AB" {...props} />,
  Java: (props) => <FaJava color="#EA2D2E" {...props} />,
  Flutter: (props) => <SiFlutter color="#02569B" {...props} />,
  Docker: (props) => <SiDocker color="#2496ED" {...props} />,
  GitHub: (props) => <SiGithub className="text-[#24292F] dark:text-white" {...props} />,
  AWS: (props) => <SiAmazonwebservices color="#FF9900" {...props} />,
  Figma: (props) => <SiFigma color="#F24E1E" {...props} />,
  OpenAI: (props) => <SiOpenai color="#10A37F" {...props} />,
  CPanel: (props) => <SiCpanel color="#FF6C2C" {...props} />,
}
